### PR TITLE
Changed from View::traits::memory_traits::TraitName to View::traits::memory_traits::is_trait_name

### PR DESCRIPTION
**Pull request by kuberry**
After most recent update to Trilinos (with deprecated code turned off), cedr_kokkos.hpp could no longer be compiled.

### CODE REVIEW

**Comment by ambrad** [comment]
Thanks, Paul. I'll look at this soon. I want to see if I need to add anything to keep COMPOSE building with older Kokkos versions.

**Comment by ambrad** [comment]
I'll use KOKKOS_VERSION as described here: https://github.com/kokkos/kokkos/issues/2787 to provide both the old and new definitions of the memory traits mask.

**Comment by kuberry** [comment]
Sounds great (and backwards compatible)! Thanks for looking into this.

**Comment by ambrad** [comment]
@kuberry Thanks for the PR. I ended up using the new KOKKOS_VERSION macro. Master now has Kokkos pre-v3 and v3 support.

Important: I've merged a commit in from develop that affects how COMPOSE is used. Next time you update your Compose version, right after you call `end_tracer_declarations`, please now also call `finish_setup`.

The idea is to separate the end of declaring metadata with `end_tracer_declarations` from potentially modifying bulk data handling with calls before `finish_setup`. For example, in Homme, we need Compose/CEDR to use MPI buffers used elsewhere in Homme and E3SM rather than create its own, to minimize memory footprint. This can now be done between `end_tracer_declarations` and `finish_setup` calls.

**Comment by ambrad** [comment]
Incorporated these changes into PR #30.

**Pull request closed without merging**
